package bean;
// Generated 08/10/2025 16:36:30 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NlcComida generated by hbm2java
 */
@Entity
@Table(name="nlc_comida"
    ,catalog="natandb"
)
public class NlcComida  implements java.io.Serializable {


     private int nlcIdComida;
     private String nlcNome;
     private String nlcSabor;
     private String nlcTipo;
     private int nlcQuantidade;
     private Date nlcValidade;
     private double nlcPreco;


    public NlcComida() {
    }

	
    public NlcComida(int nlcIdComida, String nlcNome) {
        this.nlcIdComida = nlcIdComida;
        this.nlcNome = nlcNome;
    }
    public NlcComida(int nlcIdComida, String nlcNome, String nlcSabor, String nlcTipo, int nlcQuantidade, Date nlcValidade, double nlcPreco, Set nlcCompraProdutos) {
       this.nlcIdComida = nlcIdComida;
       this.nlcNome = nlcNome;
       this.nlcSabor = nlcSabor;
       this.nlcTipo = nlcTipo;
       this.nlcQuantidade = nlcQuantidade;
       this.nlcValidade = nlcValidade;
       this.nlcPreco = nlcPreco;
    }
   
     @Id 

    
    @Column(name="nlc_id_comida", unique=true, nullable=false)
    public int getNlcIdComida() {
        return this.nlcIdComida;
    }
    
    public void setNlcIdComida(int nlcIdComida) {
        this.nlcIdComida = nlcIdComida;
    }

    
    @Column(name="nlc_nome", nullable=false, length=100)
    public String getNlcNome() {
        return this.nlcNome;
    }
    
    public void setNlcNome(String nlcNome) {
        this.nlcNome = nlcNome;
    }

    
    @Column(name="nlc_sabor", length=50)
    public String getNlcSabor() {
        return this.nlcSabor;
    }
    
    public void setNlcSabor(String nlcSabor) {
        this.nlcSabor = nlcSabor;
    }

    
    @Column(name="nlc_tipo", length=50)
    public String getNlcTipo() {
        return this.nlcTipo;
    }
    
    public void setNlcTipo(String nlcTipo) {
        this.nlcTipo = nlcTipo;
    }

    
    @Column(name="nlc_quantidade")
    public int getNlcQuantidade() {
        return this.nlcQuantidade;
    }
    
    public void setNlcQuantidade(int nlcQuantidade) {
        this.nlcQuantidade = nlcQuantidade;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="nlc_validade", length=10)
    public Date getNlcValidade() {
        return this.nlcValidade;
    }
    
    public void setNlcValidade(Date nlcValidade) {
        this.nlcValidade = nlcValidade;
    }

    
    @Column(name="nlc_preco", precision=10)
    public double getNlcPreco() {
        return this.nlcPreco;
    }
    
    public void setNlcPreco(double nlcPreco) {
        this.nlcPreco = nlcPreco;
    }

}


