package bean;
// Generated 08/10/2025 16:36:30 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NlcClientes generated by hbm2java
 */
@Entity
@Table(name="nlc_clientes"
    ,catalog="natandb"
)
public class NlcClientes  implements java.io.Serializable {


     private int nlcIdClientes;
     private String nlcNome;
     private String nlcEmail;
     private String nlcTelefone;
     private String nlcEndereco;
     private String nlcCidade;
     private String nlcEstado;
     private String nlcCep;
     private String nlcCpf;
     private Date nlcDataNascimento;
     private String nlcGenero;
     private String nlcTrabalhoFormal;
     private String nlcProfissao;
     private Character nlcAtivo;
     private Date nlcDataCadastro;

    public NlcClientes() {
    }

	
    public NlcClientes(int nlcIdClientes, String nlcNome) {
        this.nlcIdClientes = nlcIdClientes;
        this.nlcNome = nlcNome;
    }
    public NlcClientes(int nlcIdClientes, String nlcNome, String nlcEmail, String nlcTelefone, String nlcEndereco, String nlcCidade, String nlcEstado, String nlcCep, String nlcCpf, Date nlcDataNascimento, String nlcGenero, String nlcTrabalhoFormal, String nlcProfissao, Character nlcAtivo, Date nlcDataCadastro) {
       this.nlcIdClientes = nlcIdClientes;
       this.nlcNome = nlcNome;
       this.nlcEmail = nlcEmail;
       this.nlcTelefone = nlcTelefone;
       this.nlcEndereco = nlcEndereco;
       this.nlcCidade = nlcCidade;
       this.nlcEstado = nlcEstado;
       this.nlcCep = nlcCep;
       this.nlcCpf = nlcCpf;
       this.nlcDataNascimento = nlcDataNascimento;
       this.nlcGenero = nlcGenero;
       this.nlcTrabalhoFormal = nlcTrabalhoFormal;
       this.nlcProfissao = nlcProfissao;
       this.nlcAtivo = nlcAtivo;
       this.nlcDataCadastro = nlcDataCadastro;
    }
   
     @Id 

    
    @Column(name="nlc_idClientes", unique=true, nullable=false)
    public int getNlcIdClientes() {
        return this.nlcIdClientes;
    }
    
    public void setNlcIdClientes(int nlcIdClientes) {
        this.nlcIdClientes = nlcIdClientes;
    }

    
    @Column(name="nlc_nome", nullable=false, length=100)
    public String getNlcNome() {
        return this.nlcNome;
    }
    
    public void setNlcNome(String nlcNome) {
        this.nlcNome = nlcNome;
    }

    
    @Column(name="nlc_email", length=100)
    public String getNlcEmail() {
        return this.nlcEmail;
    }
    
    public void setNlcEmail(String nlcEmail) {
        this.nlcEmail = nlcEmail;
    }

    
    @Column(name="nlc_telefone", length=20)
    public String getNlcTelefone() {
        return this.nlcTelefone;
    }
    
    public void setNlcTelefone(String nlcTelefone) {
        this.nlcTelefone = nlcTelefone;
    }

    
    @Column(name="nlc_endereco", length=150)
    public String getNlcEndereco() {
        return this.nlcEndereco;
    }
    
    public void setNlcEndereco(String nlcEndereco) {
        this.nlcEndereco = nlcEndereco;
    }

    
    @Column(name="nlc_cidade", length=50)
    public String getNlcCidade() {
        return this.nlcCidade;
    }
    
    public void setNlcCidade(String nlcCidade) {
        this.nlcCidade = nlcCidade;
    }

    
    @Column(name="nlc_estado", length=50)
    public String getNlcEstado() {
        return this.nlcEstado;
    }
    
    public void setNlcEstado(String nlcEstado) {
        this.nlcEstado = nlcEstado;
    }

    
    @Column(name="nlc_cep", length=10)
    public String getNlcCep() {
        return this.nlcCep;
    }
    
    public void setNlcCep(String nlcCep) {
        this.nlcCep = nlcCep;
    }

    
    @Column(name="nlc_cpf", length=14)
    public String getNlcCpf() {
        return this.nlcCpf;
    }
    
    public void setNlcCpf(String nlcCpf) {
        this.nlcCpf = nlcCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="nlc_dataNascimento", length=10)
    public Date getNlcDataNascimento() {
        return this.nlcDataNascimento;
    }
    
    public void setNlcDataNascimento(Date nlcDataNascimento) {
        this.nlcDataNascimento = nlcDataNascimento;
    }

    
    @Column(name="nlc_genero", length=20)
    public String getNlcGenero() {
        return this.nlcGenero;
    }
    
    public void setNlcGenero(String nlcGenero) {
        this.nlcGenero = nlcGenero;
    }

    
    @Column(name="nlc_trabalhoFormal", length=50)
    public String getNlcTrabalhoFormal() {
        return this.nlcTrabalhoFormal;
    }
    
    public void setNlcTrabalhoFormal(String nlcTrabalhoFormal) {
        this.nlcTrabalhoFormal = nlcTrabalhoFormal;
    }

    
    @Column(name="nlc_profissao", length=100)
    public String getNlcProfissao() {
        return this.nlcProfissao;
    }
    
    public void setNlcProfissao(String nlcProfissao) {
        this.nlcProfissao = nlcProfissao;
    }

    
    @Column(name="nlc_ativo", length=1)
    public Character getNlcAtivo() {
        return this.nlcAtivo;
    }
    
    public void setNlcAtivo(Character nlcAtivo) {
        this.nlcAtivo = nlcAtivo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="nlc_dataCadastro", length=10)
    public Date getNlcDataCadastro() {
        return this.nlcDataCadastro;
    }
    
    public void setNlcDataCadastro(Date nlcDataCadastro) {
        this.nlcDataCadastro = nlcDataCadastro;
    }




}


