package bean;
// Generated 08/10/2025 16:36:30 by Hibernate Tools 4.3.1



import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NlcCompra generated by hbm2java
 */
@Entity
@Table(name="nlc_compra"
    ,catalog="natandb"
)
public class NlcCompra  implements java.io.Serializable {


     private int nlcIdCompra;
     private NlcUsuarios nlcUsuarios;
     private NlcVendedor nlcVendedor;
     private Date nlcData;
     private Date nlcDataPagamento;
     private double nlcTotal;
     private int nlcStatus;
     private int nlcFormaPagamento;

    public NlcCompra() {
    }

	
    public NlcCompra(int nlcIdCompra) {
        this.nlcIdCompra = nlcIdCompra;
    }
    public NlcCompra(int nlcIdCompra, NlcUsuarios nlcUsuarios, NlcVendedor nlcVendedor, Date nlcData, Date nlcDataPagamento, double nlcTotal, int nlcStatus, int nlcFormaPagamento, Set nlcCompraProdutos) {
       this.nlcIdCompra = nlcIdCompra;
       this.nlcUsuarios = nlcUsuarios;
       this.nlcVendedor = nlcVendedor;
       this.nlcData = nlcData;
       this.nlcDataPagamento = nlcDataPagamento;
       this.nlcTotal = nlcTotal;
       this.nlcStatus = nlcStatus;
       this.nlcFormaPagamento = nlcFormaPagamento;
    }
   
     @Id 

    
    @Column(name="nlc_idCompra", unique=true, nullable=false)
    public int getNlcIdCompra() {
        return this.nlcIdCompra;
    }
    
    public void setNlcIdCompra(int nlcIdCompra) {
        this.nlcIdCompra = nlcIdCompra;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="nlc_fkUsuario")
    public NlcUsuarios getNlcUsuarios() {
        return this.nlcUsuarios;
    }
    
    public void setNlcUsuarios(NlcUsuarios nlcUsuarios) {
        this.nlcUsuarios = nlcUsuarios;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="nlc_fkVendedor")
    public NlcVendedor getNlcVendedor() {
        return this.nlcVendedor;
    }
    
    public void setNlcVendedor(NlcVendedor nlcVendedor) {
        this.nlcVendedor = nlcVendedor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="nlc_data", length=10)
    public Date getNlcData() {
        return this.nlcData;
    }
    
    public void setNlcData(Date nlcData) {
        this.nlcData = nlcData;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="nlc_dataPagamento", length=10)
    public Date getNlcDataPagamento() {
        return this.nlcDataPagamento;
    }
    
    public void setNlcDataPagamento(Date nlcDataPagamento) {
        this.nlcDataPagamento = nlcDataPagamento;
    }

    
    @Column(name="nlc_total", precision=10)
    public double getNlcTotal() {
        return this.nlcTotal;
    }
    
    public void setNlcTotal(double nlcTotal) {
        this.nlcTotal = nlcTotal;
    }

    
    @Column(name="nlc_status", length=50)
    public int getNlcStatus() {
        return this.nlcStatus;
    }
    
    public void setNlcStatus(int nlcStatus) {
        this.nlcStatus = nlcStatus;
    }

    
    @Column(name="nlc_formaPagamento", length=50)
    public int getNlcFormaPagamento() {
        return this.nlcFormaPagamento;
    }
    
    public void setNlcFormaPagamento(int nlcFormaPagamento) {
        this.nlcFormaPagamento = nlcFormaPagamento;
    }




}


