package bean;
// Generated 08/10/2025 16:36:30 by Hibernate Tools 4.3.1



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * NlcCompraProduto generated by hbm2java
 */
@Entity
@Table(name="nlc_compra_produto"
    ,catalog="natandb"
)
public class NlcCompraProduto  implements java.io.Serializable {


     private int nlcIditemcompra;
     private NlcComida nlcComida;
     private NlcCompra nlcCompra;
     private int nlcQuantidade;
     private double nlcPrecoUni;
     private double nlcDesconto;

    public NlcCompraProduto() {
    }

	
    public NlcCompraProduto(int nlcIditemcompra) {
        this.nlcIditemcompra = nlcIditemcompra;
    }
    public NlcCompraProduto(int nlcIditemcompra, NlcComida nlcComida, NlcCompra nlcCompra, int nlcQuantidade, double nlcPrecoUni, double nlcDesconto) {
       this.nlcIditemcompra = nlcIditemcompra;
       this.nlcComida = nlcComida;
       this.nlcCompra = nlcCompra;
       this.nlcQuantidade = nlcQuantidade;
       this.nlcPrecoUni = nlcPrecoUni;
       this.nlcDesconto = nlcDesconto;
    }
   
     @Id 

    
    @Column(name="nlc_iditemcompra", unique=true, nullable=false)
    public int getNlcIditemcompra() {
        return this.nlcIditemcompra;
    }
    
    public void setNlcIditemcompra(int nlcIditemcompra) {
        this.nlcIditemcompra = nlcIditemcompra;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="nlc_fkcomida")
    public NlcComida getNlcComida() {
        return this.nlcComida;
    }
    
    public void setNlcComida(NlcComida nlcComida) {
        this.nlcComida = nlcComida;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="nlc_fkcompra")
    public NlcCompra getNlcCompra() {
        return this.nlcCompra;
    }
    
    public void setNlcCompra(NlcCompra nlcCompra) {
        this.nlcCompra = nlcCompra;
    }

    
    @Column(name="nlc_quantidade")
    public int getNlcQuantidade() {
        return this.nlcQuantidade;
    }
    
    public void setNlcQuantidade(int nlcQuantidade) {
        this.nlcQuantidade = nlcQuantidade;
    }

    
    @Column(name="nlc_precoUni", precision=10)
    public double getNlcPrecoUni() {
        return this.nlcPrecoUni;
    }
    
    public void setNlcPrecoUni(double nlcPrecoUni) {
        this.nlcPrecoUni = nlcPrecoUni;
    }

    
    @Column(name="nlc_desconto", precision=10)
    public double getNlcDesconto() {
        return this.nlcDesconto;
    }
    
    public void setNlcDesconto(double nlcDesconto) {
        this.nlcDesconto = nlcDesconto;
    }




}


