package bean;
// Generated 08/10/2025 16:36:30 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NlcUsuarios generated by hbm2java
 */
@Entity
@Table(name="nlc_usuarios"
    ,catalog="natandb"
)
public class NlcUsuarios  implements java.io.Serializable {


     private int nlcIdusuarios;
     private String nlcNome;
     private String nlcApelido;
     private String nlcCpf;
     private Date nlcDataNascimento;
     private String nlcSenha;
     private Integer nlcNivel;
     private Character nlcAtivo;
     private Set nlcCompras = new HashSet(0);

    public NlcUsuarios() {
    }

	
    public NlcUsuarios(int nlcIdusuarios, String nlcNome) {
        this.nlcIdusuarios = nlcIdusuarios;
        this.nlcNome = nlcNome;
    }
    public NlcUsuarios(int nlcIdusuarios, String nlcNome, String nlcApelido, String nlcCpf, Date nlcDataNascimento, String nlcSenha, Integer nlcNivel, Character nlcAtivo, Set nlcCompras) {
       this.nlcIdusuarios = nlcIdusuarios;
       this.nlcNome = nlcNome;
       this.nlcApelido = nlcApelido;
       this.nlcCpf = nlcCpf;
       this.nlcDataNascimento = nlcDataNascimento;
       this.nlcSenha = nlcSenha;
       this.nlcNivel = nlcNivel;
       this.nlcAtivo = nlcAtivo;
       this.nlcCompras = nlcCompras;
    }
   
     @Id 

    
    @Column(name="nlc_idusuarios", unique=true, nullable=false)
    public int getNlcIdusuarios() {
        return this.nlcIdusuarios;
    }
    
    public void setNlcIdusuarios(int nlcIdusuarios) {
        this.nlcIdusuarios = nlcIdusuarios;
    }

    
    @Column(name="nlc_nome", nullable=false, length=100)
    public String getNlcNome() {
        return this.nlcNome;
    }
    
    public void setNlcNome(String nlcNome) {
        this.nlcNome = nlcNome;
    }

    
    @Column(name="nlc_apelido", length=50)
    public String getNlcApelido() {
        return this.nlcApelido;
    }
    
    public void setNlcApelido(String nlcApelido) {
        this.nlcApelido = nlcApelido;
    }

    
    @Column(name="nlc_cpf", length=20)
    public String getNlcCpf() {
        return this.nlcCpf;
    }
    
    public void setNlcCpf(String nlcCpf) {
        this.nlcCpf = nlcCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="nlc_dataNascimento", length=10)
    public Date getNlcDataNascimento() {
        return this.nlcDataNascimento;
    }
    
    public void setNlcDataNascimento(Date nlcDataNascimento) {
        this.nlcDataNascimento = nlcDataNascimento;
    }

    
    @Column(name="nlc_senha", length=100)
    public String getNlcSenha() {
        return this.nlcSenha;
    }
    
    public void setNlcSenha(String nlcSenha) {
        this.nlcSenha = nlcSenha;
    }

    
    @Column(name="nlc_nivel")
    public Integer getNlcNivel() {
        return this.nlcNivel;
    }
    
    public void setNlcNivel(Integer nlcNivel) {
        this.nlcNivel = nlcNivel;
    }

    
    @Column(name="nlc_ativo", length=1)
    public Character getNlcAtivo() {
        return this.nlcAtivo;
    }
    
    public void setNlcAtivo(Character nlcAtivo) {
        this.nlcAtivo = nlcAtivo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nlcUsuarios")
    public Set getNlcCompras() {
        return this.nlcCompras;
    }
    
    public void setNlcCompras(Set nlcCompras) {
        this.nlcCompras = nlcCompras;
    }




}


