package bean;
// Generated 08/10/2025 16:36:30 by Hibernate Tools 4.3.1




import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NlcVendedor generated by hbm2java
 */
@Entity
@Table(name="nlc_vendedor"
    ,catalog="natandb"
)
public class NlcVendedor  implements java.io.Serializable {


     private int nlcIdVendedor;
     private String nlcNome;
     private String nlcTelefone;
     private String nlcCpf;
     private String nlcTurno;
     private double nlcSalario;
     private String nlcEmail;

    public NlcVendedor() {
    }

	
    public NlcVendedor(int nlcIdVendedor, String nlcNome) {
        this.nlcIdVendedor = nlcIdVendedor;
        this.nlcNome = nlcNome;
    }
    public NlcVendedor(int nlcIdVendedor, String nlcNome, String nlcTelefone, String nlcCpf, String nlcTurno, double nlcSalario, String nlcEmail, Set nlcCompras) {
       this.nlcIdVendedor = nlcIdVendedor;
       this.nlcNome = nlcNome;
       this.nlcTelefone = nlcTelefone;
       this.nlcCpf = nlcCpf;
       this.nlcTurno = nlcTurno;
       this.nlcSalario = nlcSalario;
       this.nlcEmail = nlcEmail;

    }
   
     @Id 

    
    @Column(name="nlc_idVendedor", unique=true, nullable=false)
    public int getNlcIdVendedor() {
        return this.nlcIdVendedor;
    }
    
    public void setNlcIdVendedor(int nlcIdVendedor) {
        this.nlcIdVendedor = nlcIdVendedor;
    }

    
    @Column(name="nlc_nome", nullable=false, length=100)
    public String getNlcNome() {
        return this.nlcNome;
    }
    
    public void setNlcNome(String nlcNome) {
        this.nlcNome = nlcNome;
    }

    
    @Column(name="nlc_telefone", length=11)
    public String getNlcTelefone() {
        return this.nlcTelefone;
    }
    
    public void setNlcTelefone(String nlcTelefone) {
        this.nlcTelefone = nlcTelefone;
    }

    
    @Column(name="nlc_cpf", length=14)
    public String getNlcCpf() {
        return this.nlcCpf;
    }
    
    public void setNlcCpf(String nlcCpf) {
        this.nlcCpf = nlcCpf;
    }

    
    @Column(name="nlc_turno", length=20)
    public String getNlcTurno() {
        return this.nlcTurno;
    }
    
    public void setNlcTurno(String nlcTurno) {
        this.nlcTurno = nlcTurno;
    }

    
    @Column(name="nlc_salario", precision=10)
    public double getNlcSalario() {
        return this.nlcSalario;
    }
    
    public void setNlcSalario(double nlcSalario) {
        this.nlcSalario = nlcSalario;
    }

    
    @Column(name="nlc_email", length=100)
    public String getNlcEmail() {
        return this.nlcEmail;
    }
    
    public void setNlcEmail(String nlcEmail) {
        this.nlcEmail = nlcEmail;
    }






}


